#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4InventorySerialization
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Inventory")]
	public partial class SerializationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMPI(MPI instance);
    partial void UpdateMPI(MPI instance);
    partial void DeleteMPI(MPI instance);
    partial void InsertMPI_History(MPI_History instance);
    partial void UpdateMPI_History(MPI_History instance);
    partial void DeleteMPI_History(MPI_History instance);
    partial void InsertIR(IR instance);
    partial void UpdateIR(IR instance);
    partial void DeleteIR(IR instance);
    partial void InsertIR_History(IR_History instance);
    partial void UpdateIR_History(IR_History instance);
    partial void DeleteIR_History(IR_History instance);
    partial void InsertKits(Kits instance);
    partial void UpdateKits(Kits instance);
    partial void DeleteKits(Kits instance);
    partial void InsertDelivery(Delivery instance);
    partial void UpdateDelivery(Delivery instance);
    partial void DeleteDelivery(Delivery instance);
    partial void InsertDelivery_History(Delivery_History instance);
    partial void UpdateDelivery_History(Delivery_History instance);
    partial void DeleteDelivery_History(Delivery_History instance);
    #endregion
		
		public SerializationDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InventoryConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SerializationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerializationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerializationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SerializationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MPI> MPIs
		{
			get
			{
				return this.GetTable<MPI>();
			}
		}
		
		public System.Data.Linq.Table<MPI_History> MPI_Histories
		{
			get
			{
				return this.GetTable<MPI_History>();
			}
		}
		
		public System.Data.Linq.Table<IR> IRs
		{
			get
			{
				return this.GetTable<IR>();
			}
		}
		
		public System.Data.Linq.Table<IR_History> IR_Histories
		{
			get
			{
				return this.GetTable<IR_History>();
			}
		}
		
		public System.Data.Linq.Table<Kits> Kits
		{
			get
			{
				return this.GetTable<Kits>();
			}
		}
		
		public System.Data.Linq.Table<Delivery> Deliveries
		{
			get
			{
				return this.GetTable<Delivery>();
			}
		}
		
		public System.Data.Linq.Table<Delivery_History> Delivery_Histories
		{
			get
			{
				return this.GetTable<Delivery_History>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Delivery_Header")]
		public ISingleResult<sp_Delivery_HeaderResult> sp_Delivery_Header([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="NVarChar(50)")] string dOCNUM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM);
			return ((ISingleResult<sp_Delivery_HeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Delivery_History")]
		public ISingleResult<sp_Delivery_HistoryResult> sp_Delivery_History()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_Delivery_HistoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Delivery_Synch")]
		public ISingleResult<sp_Delivery_SynchResult> sp_Delivery_Synch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((ISingleResult<sp_Delivery_SynchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Delivery_Verify")]
		public ISingleResult<sp_Delivery_VerifyResult> sp_Delivery_Verify([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((ISingleResult<sp_Delivery_VerifyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetSAPItems")]
		public ISingleResult<sp_GetSAPItemsResult> sp_GetSAPItems()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_GetSAPItemsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GoodsIssue_IR_Synch")]
		public ISingleResult<sp_GoodsIssue_IR_SynchResult> sp_GoodsIssue_IR_Synch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((ISingleResult<sp_GoodsIssue_IR_SynchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GoodsIssue_IR_Verify")]
		public ISingleResult<sp_GoodsIssue_IR_VerifyResult> sp_GoodsIssue_IR_Verify([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((ISingleResult<sp_GoodsIssue_IR_VerifyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReturnIRByLineItem")]
		public int sp_ReturnIRByLineItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, uSERNAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IR_Header")]
		public ISingleResult<sp_IR_HeaderResult> sp_IR_Header([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="NVarChar(50)")] string dOCNUM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM);
			return ((ISingleResult<sp_IR_HeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_IR_History")]
		public ISingleResult<sp_IR_HistoryResult> sp_IR_History()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_IR_HistoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReturnDelivery")]
		public int sp_ReturnDelivery([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReturnDeliveryByLineItem")]
		public int sp_ReturnDeliveryByLineItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, uSERNAME);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ReturnGoodsIssue_IR")]
		public int sp_ReturnGoodsIssue_IR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOCNUM", DbType="Int")] System.Nullable<int> dOCNUM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(50)")] string uSERNAME)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dOCNUM, uSERNAME);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_MaintainProductID")]
	public partial class MPI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PRODUCTID;
		
		private string _ITEMCODE;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    #endregion
		
		public MPI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_MAINTAINPRODUCTID_HISTORY")]
	public partial class MPI_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TYPE;
		
		private System.DateTime _DATE;
		
		private string _PRODUCTID;
		
		private string _ITEMCODE;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		private string _USERNAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnDATEChanging(System.DateTime value);
    partial void OnDATEChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public MPI_History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_GOODSISSUE_IR_OUT")]
	public partial class IR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DOCTYPE;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		private string _SERIALCODE;
		
		private System.Nullable<bool> _VERIFIED;
		
		private string _USERNAME;
		
		private string _VERIFIEDBY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCTYPEChanging(string value);
    partial void OnDOCTYPEChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnDOCNUMChanging(int value);
    partial void OnDOCNUMChanged();
    partial void OnSERIALNUMChanging(int value);
    partial void OnSERIALNUMChanged();
    partial void OnDOCENTRYChanging(System.Nullable<int> value);
    partial void OnDOCENTRYChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnLINENUMChanging(System.Nullable<int> value);
    partial void OnLINENUMChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnDSCRIPTIONChanging(string value);
    partial void OnDSCRIPTIONChanged();
    partial void OnALTTEXTChanging(string value);
    partial void OnALTTEXTChanged();
    partial void OnQUANTITYChanging(System.Nullable<decimal> value);
    partial void OnQUANTITYChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    partial void OnSERIALCODEChanging(string value);
    partial void OnSERIALCODEChanged();
    partial void OnVERIFIEDChanging(System.Nullable<bool> value);
    partial void OnVERIFIEDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnVERIFIEDBYChanging(string value);
    partial void OnVERIFIEDBYChanged();
    #endregion
		
		public IR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="NVarChar(50)")]
		public string DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this.OnDOCNUMChanging(value);
					this.SendPropertyChanging();
					this._DOCNUM = value;
					this.SendPropertyChanged("DOCNUM");
					this.OnDOCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this.OnSERIALNUMChanging(value);
					this.SendPropertyChanging();
					this._SERIALNUM = value;
					this.SendPropertyChanged("SERIALNUM");
					this.OnSERIALNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this.OnDOCENTRYChanging(value);
					this.SendPropertyChanging();
					this._DOCENTRY = value;
					this.SendPropertyChanged("DOCENTRY");
					this.OnDOCENTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this.OnLINENUMChanging(value);
					this.SendPropertyChanging();
					this._LINENUM = value;
					this.SendPropertyChanged("LINENUM");
					this.OnLINENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this.OnDSCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DSCRIPTION = value;
					this.SendPropertyChanged("DSCRIPTION");
					this.OnDSCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this.OnALTTEXTChanging(value);
					this.SendPropertyChanging();
					this._ALTTEXT = value;
					this.SendPropertyChanged("ALTTEXT");
					this.OnALTTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this.OnSERIALCODEChanging(value);
					this.SendPropertyChanging();
					this._SERIALCODE = value;
					this.SendPropertyChanged("SERIALCODE");
					this.OnSERIALCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="Bit")]
		public System.Nullable<bool> VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this.OnVERIFIEDChanging(value);
					this.SendPropertyChanging();
					this._VERIFIED = value;
					this.SendPropertyChanged("VERIFIED");
					this.OnVERIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDBY", DbType="NVarChar(50)")]
		public string VERIFIEDBY
		{
			get
			{
				return this._VERIFIEDBY;
			}
			set
			{
				if ((this._VERIFIEDBY != value))
				{
					this.OnVERIFIEDBYChanging(value);
					this.SendPropertyChanging();
					this._VERIFIEDBY = value;
					this.SendPropertyChanged("VERIFIEDBY");
					this.OnVERIFIEDBYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_GOODSISSUE_IR_OUT_HISTORY")]
	public partial class IR_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DOCTYPE;
		
		private System.DateTime _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		private string _SERIALCODE;
		
		private System.Nullable<bool> _VERIFIED;
		
		private string _USERNAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCTYPEChanging(string value);
    partial void OnDOCTYPEChanged();
    partial void OnDATEChanging(System.DateTime value);
    partial void OnDATEChanged();
    partial void OnDOCNUMChanging(int value);
    partial void OnDOCNUMChanged();
    partial void OnSERIALNUMChanging(int value);
    partial void OnSERIALNUMChanged();
    partial void OnDOCENTRYChanging(System.Nullable<int> value);
    partial void OnDOCENTRYChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnLINENUMChanging(System.Nullable<int> value);
    partial void OnLINENUMChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnDSCRIPTIONChanging(string value);
    partial void OnDSCRIPTIONChanged();
    partial void OnALTTEXTChanging(string value);
    partial void OnALTTEXTChanged();
    partial void OnQUANTITYChanging(System.Nullable<decimal> value);
    partial void OnQUANTITYChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    partial void OnSERIALCODEChanging(string value);
    partial void OnSERIALCODEChanged();
    partial void OnVERIFIEDChanging(System.Nullable<bool> value);
    partial void OnVERIFIEDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public IR_History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="NVarChar(50)")]
		public string DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this.OnDOCNUMChanging(value);
					this.SendPropertyChanging();
					this._DOCNUM = value;
					this.SendPropertyChanged("DOCNUM");
					this.OnDOCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this.OnSERIALNUMChanging(value);
					this.SendPropertyChanging();
					this._SERIALNUM = value;
					this.SendPropertyChanged("SERIALNUM");
					this.OnSERIALNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this.OnDOCENTRYChanging(value);
					this.SendPropertyChanging();
					this._DOCENTRY = value;
					this.SendPropertyChanged("DOCENTRY");
					this.OnDOCENTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this.OnLINENUMChanging(value);
					this.SendPropertyChanging();
					this._LINENUM = value;
					this.SendPropertyChanged("LINENUM");
					this.OnLINENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this.OnDSCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DSCRIPTION = value;
					this.SendPropertyChanged("DSCRIPTION");
					this.OnDSCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this.OnALTTEXTChanging(value);
					this.SendPropertyChanging();
					this._ALTTEXT = value;
					this.SendPropertyChanged("ALTTEXT");
					this.OnALTTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this.OnSERIALCODEChanging(value);
					this.SendPropertyChanging();
					this._SERIALCODE = value;
					this.SendPropertyChanged("SERIALCODE");
					this.OnSERIALCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="Bit")]
		public System.Nullable<bool> VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this.OnVERIFIEDChanging(value);
					this.SendPropertyChanging();
					this._VERIFIED = value;
					this.SendPropertyChanged("VERIFIED");
					this.OnVERIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_MAINTAINKITS")]
	public partial class Kits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ITEMCODE;
		
		private string _ALTERNATETEXT;
		
		private string _PRODUCTID;
		
		private int _QUANTITY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnALTERNATETEXTChanging(string value);
    partial void OnALTERNATETEXTChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnQUANTITYChanging(int value);
    partial void OnQUANTITYChanged();
    #endregion
		
		public Kits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTERNATETEXT", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ALTERNATETEXT
		{
			get
			{
				return this._ALTERNATETEXT;
			}
			set
			{
				if ((this._ALTERNATETEXT != value))
				{
					this.OnALTERNATETEXTChanging(value);
					this.SendPropertyChanging();
					this._ALTERNATETEXT = value;
					this.SendPropertyChanged("ALTERNATETEXT");
					this.OnALTERNATETEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int NOT NULL")]
		public int QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_SERIALNUMBERS_OUT")]
	public partial class Delivery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DOCTYPE;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		private string _SERIALCODE;
		
		private System.Nullable<bool> _VERIFIED;
		
		private string _USERNAME;
		
		private string _VERIFIEDBY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCTYPEChanging(string value);
    partial void OnDOCTYPEChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnDOCNUMChanging(int value);
    partial void OnDOCNUMChanged();
    partial void OnSERIALNUMChanging(int value);
    partial void OnSERIALNUMChanged();
    partial void OnDOCENTRYChanging(System.Nullable<int> value);
    partial void OnDOCENTRYChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnLINENUMChanging(System.Nullable<int> value);
    partial void OnLINENUMChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnDSCRIPTIONChanging(string value);
    partial void OnDSCRIPTIONChanged();
    partial void OnALTTEXTChanging(string value);
    partial void OnALTTEXTChanged();
    partial void OnQUANTITYChanging(System.Nullable<decimal> value);
    partial void OnQUANTITYChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    partial void OnSERIALCODEChanging(string value);
    partial void OnSERIALCODEChanged();
    partial void OnVERIFIEDChanging(System.Nullable<bool> value);
    partial void OnVERIFIEDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnVERIFIEDBYChanging(string value);
    partial void OnVERIFIEDBYChanged();
    #endregion
		
		public Delivery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="NVarChar(50)")]
		public string DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this.OnDOCNUMChanging(value);
					this.SendPropertyChanging();
					this._DOCNUM = value;
					this.SendPropertyChanged("DOCNUM");
					this.OnDOCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this.OnSERIALNUMChanging(value);
					this.SendPropertyChanging();
					this._SERIALNUM = value;
					this.SendPropertyChanged("SERIALNUM");
					this.OnSERIALNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this.OnDOCENTRYChanging(value);
					this.SendPropertyChanging();
					this._DOCENTRY = value;
					this.SendPropertyChanged("DOCENTRY");
					this.OnDOCENTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this.OnLINENUMChanging(value);
					this.SendPropertyChanging();
					this._LINENUM = value;
					this.SendPropertyChanged("LINENUM");
					this.OnLINENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this.OnDSCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DSCRIPTION = value;
					this.SendPropertyChanged("DSCRIPTION");
					this.OnDSCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this.OnALTTEXTChanging(value);
					this.SendPropertyChanging();
					this._ALTTEXT = value;
					this.SendPropertyChanged("ALTTEXT");
					this.OnALTTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this.OnSERIALCODEChanging(value);
					this.SendPropertyChanging();
					this._SERIALCODE = value;
					this.SendPropertyChanged("SERIALCODE");
					this.OnSERIALCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="Bit")]
		public System.Nullable<bool> VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this.OnVERIFIEDChanging(value);
					this.SendPropertyChanging();
					this._VERIFIED = value;
					this.SendPropertyChanged("VERIFIED");
					this.OnVERIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDBY", DbType="NVarChar(50)")]
		public string VERIFIEDBY
		{
			get
			{
				return this._VERIFIEDBY;
			}
			set
			{
				if ((this._VERIFIEDBY != value))
				{
					this.OnVERIFIEDBYChanging(value);
					this.SendPropertyChanging();
					this._VERIFIEDBY = value;
					this.SendPropertyChanged("VERIFIEDBY");
					this.OnVERIFIEDBYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C4_SERIALNUMBERS_OUT_HISTORY")]
	public partial class Delivery_History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DOCTYPE;
		
		private System.DateTime _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		private string _SERIALCODE;
		
		private System.Nullable<bool> _VERIFIED;
		
		private string _USERNAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCTYPEChanging(string value);
    partial void OnDOCTYPEChanged();
    partial void OnDATEChanging(System.DateTime value);
    partial void OnDATEChanged();
    partial void OnDOCNUMChanging(int value);
    partial void OnDOCNUMChanged();
    partial void OnSERIALNUMChanging(int value);
    partial void OnSERIALNUMChanged();
    partial void OnDOCENTRYChanging(System.Nullable<int> value);
    partial void OnDOCENTRYChanged();
    partial void OnDOCDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDOCDATEChanged();
    partial void OnLINENUMChanging(System.Nullable<int> value);
    partial void OnLINENUMChanged();
    partial void OnITEMCODEChanging(string value);
    partial void OnITEMCODEChanged();
    partial void OnDSCRIPTIONChanging(string value);
    partial void OnDSCRIPTIONChanged();
    partial void OnALTTEXTChanging(string value);
    partial void OnALTTEXTChanged();
    partial void OnQUANTITYChanging(System.Nullable<decimal> value);
    partial void OnQUANTITYChanged();
    partial void OnPRODUCTIDChanging(string value);
    partial void OnPRODUCTIDChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnNOSERIALIZATIONChanging(System.Nullable<bool> value);
    partial void OnNOSERIALIZATIONChanged();
    partial void OnSMARTCODEONLYChanging(System.Nullable<bool> value);
    partial void OnSMARTCODEONLYChanged();
    partial void OnSERIALCODEChanging(string value);
    partial void OnSERIALCODEChanged();
    partial void OnVERIFIEDChanging(System.Nullable<bool> value);
    partial void OnVERIFIEDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public Delivery_History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCTYPE", DbType="NVarChar(50)")]
		public string DOCTYPE
		{
			get
			{
				return this._DOCTYPE;
			}
			set
			{
				if ((this._DOCTYPE != value))
				{
					this.OnDOCTYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCTYPE = value;
					this.SendPropertyChanged("DOCTYPE");
					this.OnDOCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this.OnDOCNUMChanging(value);
					this.SendPropertyChanging();
					this._DOCNUM = value;
					this.SendPropertyChanged("DOCNUM");
					this.OnDOCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this.OnSERIALNUMChanging(value);
					this.SendPropertyChanging();
					this._SERIALNUM = value;
					this.SendPropertyChanged("SERIALNUM");
					this.OnSERIALNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this.OnDOCENTRYChanging(value);
					this.SendPropertyChanging();
					this._DOCENTRY = value;
					this.SendPropertyChanged("DOCENTRY");
					this.OnDOCENTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this.OnDOCDATEChanging(value);
					this.SendPropertyChanging();
					this._DOCDATE = value;
					this.SendPropertyChanged("DOCDATE");
					this.OnDOCDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this.OnLINENUMChanging(value);
					this.SendPropertyChanging();
					this._LINENUM = value;
					this.SendPropertyChanged("LINENUM");
					this.OnLINENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this.OnITEMCODEChanging(value);
					this.SendPropertyChanging();
					this._ITEMCODE = value;
					this.SendPropertyChanged("ITEMCODE");
					this.OnITEMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this.OnDSCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DSCRIPTION = value;
					this.SendPropertyChanged("DSCRIPTION");
					this.OnDSCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this.OnALTTEXTChanging(value);
					this.SendPropertyChanging();
					this._ALTTEXT = value;
					this.SendPropertyChanged("ALTTEXT");
					this.OnALTTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(19,6)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this.OnPRODUCTIDChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTID = value;
					this.SendPropertyChanged("PRODUCTID");
					this.OnPRODUCTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this.OnNOSERIALIZATIONChanging(value);
					this.SendPropertyChanging();
					this._NOSERIALIZATION = value;
					this.SendPropertyChanged("NOSERIALIZATION");
					this.OnNOSERIALIZATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this.OnSMARTCODEONLYChanging(value);
					this.SendPropertyChanging();
					this._SMARTCODEONLY = value;
					this.SendPropertyChanged("SMARTCODEONLY");
					this.OnSMARTCODEONLYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this.OnSERIALCODEChanging(value);
					this.SendPropertyChanging();
					this._SERIALCODE = value;
					this.SendPropertyChanged("SERIALCODE");
					this.OnSERIALCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="Bit")]
		public System.Nullable<bool> VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this.OnVERIFIEDChanging(value);
					this.SendPropertyChanging();
					this._VERIFIED = value;
					this.SendPropertyChanged("VERIFIED");
					this.OnVERIFIEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class sp_Delivery_HeaderResult
	{
		
		private string _COLUMN1;
		
		private string _COLUMN2;
		
		private int _DOCNUM;
		
		public sp_Delivery_HeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN1", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string COLUMN1
		{
			get
			{
				return this._COLUMN1;
			}
			set
			{
				if ((this._COLUMN1 != value))
				{
					this._COLUMN1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN2", DbType="NVarChar(254)")]
		public string COLUMN2
		{
			get
			{
				return this._COLUMN2;
			}
			set
			{
				if ((this._COLUMN2 != value))
				{
					this._COLUMN2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
	}
	
	public partial class sp_Delivery_HistoryResult
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _SERIALCODE;
		
		private string _VERIFIED;
		
		private string _USERNAME;
		
		private string _VERIFIEDBY;
		
		public sp_Delivery_HistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL")]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this._SERIALNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this._DOCENTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this._DOCDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this._LINENUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this._ITEMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this._DSCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this._ALTTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this._PRODUCTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this._SERIALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="VarChar(8)")]
		public string VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this._VERIFIED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDBY", DbType="NVarChar(50)")]
		public string VERIFIEDBY
		{
			get
			{
				return this._VERIFIEDBY;
			}
			set
			{
				if ((this._VERIFIEDBY != value))
				{
					this._VERIFIEDBY = value;
				}
			}
		}
	}
	
	public partial class sp_Delivery_SynchResult
	{
		
		private int _ID;
		
		private int _DOCNUM;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private int _SERIALNUM;
		
		private string _SERIALCODE;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		public sp_Delivery_SynchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this._DOCDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this._ITEMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this._DSCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this._ALTTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL")]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this._SERIALNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this._SERIALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this._PRODUCTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this._COLOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this._NOSERIALIZATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this._SMARTCODEONLY = value;
				}
			}
		}
	}
	
	public partial class sp_Delivery_VerifyResult
	{
		
		private System.Nullable<int> _VERIFIEDCOUNT;
		
		public sp_Delivery_VerifyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDCOUNT", DbType="Int")]
		public System.Nullable<int> VERIFIEDCOUNT
		{
			get
			{
				return this._VERIFIEDCOUNT;
			}
			set
			{
				if ((this._VERIFIEDCOUNT != value))
				{
					this._VERIFIEDCOUNT = value;
				}
			}
		}
	}
	
	public partial class sp_GetSAPItemsResult
	{
		
		private string _sapitemcode;
		
		public sp_GetSAPItemsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sapitemcode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string sapitemcode
		{
			get
			{
				return this._sapitemcode;
			}
			set
			{
				if ((this._sapitemcode != value))
				{
					this._sapitemcode = value;
				}
			}
		}
	}
	
	public partial class sp_GoodsIssue_IR_SynchResult
	{
		
		private int _ID;
		
		private int _DOCNUM;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private int _SERIALNUM;
		
		private string _SERIALCODE;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _COLOR;
		
		private System.Nullable<bool> _NOSERIALIZATION;
		
		private System.Nullable<bool> _SMARTCODEONLY;
		
		public sp_GoodsIssue_IR_SynchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this._DOCDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this._ITEMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this._DSCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this._ALTTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL")]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this._SERIALNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this._SERIALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this._PRODUCTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="NVarChar(50)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this._COLOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSERIALIZATION", DbType="Bit")]
		public System.Nullable<bool> NOSERIALIZATION
		{
			get
			{
				return this._NOSERIALIZATION;
			}
			set
			{
				if ((this._NOSERIALIZATION != value))
				{
					this._NOSERIALIZATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMARTCODEONLY", DbType="Bit")]
		public System.Nullable<bool> SMARTCODEONLY
		{
			get
			{
				return this._SMARTCODEONLY;
			}
			set
			{
				if ((this._SMARTCODEONLY != value))
				{
					this._SMARTCODEONLY = value;
				}
			}
		}
	}
	
	public partial class sp_GoodsIssue_IR_VerifyResult
	{
		
		private System.Nullable<int> _VERIFIEDCOUNT;
		
		public sp_GoodsIssue_IR_VerifyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDCOUNT", DbType="Int")]
		public System.Nullable<int> VERIFIEDCOUNT
		{
			get
			{
				return this._VERIFIEDCOUNT;
			}
			set
			{
				if ((this._VERIFIEDCOUNT != value))
				{
					this._VERIFIEDCOUNT = value;
				}
			}
		}
	}
	
	public partial class sp_IR_HeaderResult
	{
		
		private string _COLUMN1;
		
		private string _COLUMN2;
		
		private int _DOCNUM;
		
		public sp_IR_HeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN1", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string COLUMN1
		{
			get
			{
				return this._COLUMN1;
			}
			set
			{
				if ((this._COLUMN1 != value))
				{
					this._COLUMN1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMN2", DbType="NVarChar(254)")]
		public string COLUMN2
		{
			get
			{
				return this._COLUMN2;
			}
			set
			{
				if ((this._COLUMN2 != value))
				{
					this._COLUMN2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
	}
	
	public partial class sp_IR_HistoryResult
	{
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private int _DOCNUM;
		
		private int _SERIALNUM;
		
		private System.Nullable<int> _DOCENTRY;
		
		private System.Nullable<System.DateTime> _DOCDATE;
		
		private System.Nullable<int> _LINENUM;
		
		private string _ITEMCODE;
		
		private string _DSCRIPTION;
		
		private string _ALTTEXT;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private string _PRODUCTID;
		
		private string _SERIALCODE;
		
		private string _VERIFIED;
		
		private string _USERNAME;
		
		private string _VERIFIEDBY;
		
		public sp_IR_HistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCNUM", DbType="Int NOT NULL")]
		public int DOCNUM
		{
			get
			{
				return this._DOCNUM;
			}
			set
			{
				if ((this._DOCNUM != value))
				{
					this._DOCNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALNUM", DbType="Int NOT NULL")]
		public int SERIALNUM
		{
			get
			{
				return this._SERIALNUM;
			}
			set
			{
				if ((this._SERIALNUM != value))
				{
					this._SERIALNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCENTRY", DbType="Int")]
		public System.Nullable<int> DOCENTRY
		{
			get
			{
				return this._DOCENTRY;
			}
			set
			{
				if ((this._DOCENTRY != value))
				{
					this._DOCENTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOCDATE
		{
			get
			{
				return this._DOCDATE;
			}
			set
			{
				if ((this._DOCDATE != value))
				{
					this._DOCDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINENUM", DbType="Int")]
		public System.Nullable<int> LINENUM
		{
			get
			{
				return this._LINENUM;
			}
			set
			{
				if ((this._LINENUM != value))
				{
					this._LINENUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMCODE", DbType="NVarChar(20)")]
		public string ITEMCODE
		{
			get
			{
				return this._ITEMCODE;
			}
			set
			{
				if ((this._ITEMCODE != value))
				{
					this._ITEMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCRIPTION", DbType="NVarChar(100)")]
		public string DSCRIPTION
		{
			get
			{
				return this._DSCRIPTION;
			}
			set
			{
				if ((this._DSCRIPTION != value))
				{
					this._DSCRIPTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALTTEXT", DbType="NVarChar(100)")]
		public string ALTTEXT
		{
			get
			{
				return this._ALTTEXT;
			}
			set
			{
				if ((this._ALTTEXT != value))
				{
					this._ALTTEXT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTID", DbType="NVarChar(20)")]
		public string PRODUCTID
		{
			get
			{
				return this._PRODUCTID;
			}
			set
			{
				if ((this._PRODUCTID != value))
				{
					this._PRODUCTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIALCODE", DbType="NVarChar(50)")]
		public string SERIALCODE
		{
			get
			{
				return this._SERIALCODE;
			}
			set
			{
				if ((this._SERIALCODE != value))
				{
					this._SERIALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIED", DbType="VarChar(8)")]
		public string VERIFIED
		{
			get
			{
				return this._VERIFIED;
			}
			set
			{
				if ((this._VERIFIED != value))
				{
					this._VERIFIED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFIEDBY", DbType="NVarChar(50)")]
		public string VERIFIEDBY
		{
			get
			{
				return this._VERIFIEDBY;
			}
			set
			{
				if ((this._VERIFIEDBY != value))
				{
					this._VERIFIEDBY = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
