//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4InventorySerialization.Master {
    
    
    public partial class Site1 {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// EasymenuMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.EasyMenu EasymenuMain;
        
        /// <summary>
        /// MenuItem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem1;
        
        /// <summary>
        /// mainMenuSeparator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator mainMenuSeparator1;
        
        /// <summary>
        /// MenuItem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem2;
        
        /// <summary>
        /// MenuSeparator2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator MenuSeparator2;
        
        /// <summary>
        /// MenuItem3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem3;
        
        /// <summary>
        /// mainMenuSeparator2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator mainMenuSeparator2;
        
        /// <summary>
        /// MenuItem4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem4;
        
        /// <summary>
        /// MenuSeparator3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator MenuSeparator3;
        
        /// <summary>
        /// MenuItem5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem5;
        
        /// <summary>
        /// MenuSeparator5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator MenuSeparator5;
        
        /// <summary>
        /// MenuItem6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem6;
        
        /// <summary>
        /// MenuSeparator4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator MenuSeparator4;
        
        /// <summary>
        /// MenuItem8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem8;
        
        /// <summary>
        /// MenuSeparator6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuSeparator MenuSeparator6;
        
        /// <summary>
        /// MenuItem7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OboutInc.EasyMenu_Pro.MenuItem MenuItem7;
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
