// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ShipToolAutomatedTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public partial class UIMap
    {
        
        
        
        /// <summary>
        /// Log into System Successfully
        /// </summary>
        public void LoginSuccess()
        {
            #region Variable Declarations
            WinCustom uIItemCustom = this.UIC4SerializationAppliWindow.UIItemWindow1.UIItemCustom;
            WinControl uIItemDocument = this.UIC4SerializationAppliWindow.UIItemWindow1.UIItemDocument;
            #endregion

            // Click custom control
            Mouse.Click(uIItemCustom, new Point(114, 16));

            // Type 'jleung{Tab}' in custom control
            Keyboard.SendKeys(uIItemCustom, this.LoginSuccessParams.UIItemCustomSendKeys, ModifierKeys.None);

            // Type '1234{+}five' in custom control
            Keyboard.SendKeys(uIItemCustom, this.LoginSuccessParams.UIItemCustomSendKeys1, ModifierKeys.None);

            // Click document
            Mouse.Click(uIItemDocument, new Point(242, 351));
        }
        
      
        public virtual LoginSuccessParams LoginSuccessParams
        {
            get
            {
                if ((this.mLoginSuccessParams == null))
                {
                    this.mLoginSuccessParams = new LoginSuccessParams();
                }
                return this.mLoginSuccessParams;
            }
        }
        
        public UIC4SerializationAppliWindow UIC4SerializationAppliWindow
        {
            get 
            {
                if ((this.mUIC4SerializationAppliWindow == null))
                {
                    this.mUIC4SerializationAppliWindow = new UIC4SerializationAppliWindow();
                }
                return this.mUIC4SerializationAppliWindow;
            }
        }
        
        public UIStartmenuWindow UIStartmenuWindow
        {
            get
            {
                if ((this.mUIStartmenuWindow == null))
                {
                    this.mUIStartmenuWindow = new UIStartmenuWindow();
                }
                return this.mUIStartmenuWindow;
            }
        }
        
        public UIItemWindow4 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow4();
                }
                return this.mUIItemWindow;
            }
        }
        
        #region Fields
        
        private LoginSuccessParams mLoginSuccessParams;
        
        private UIC4SerializationAppliWindow mUIC4SerializationAppliWindow;
        
        private UIStartmenuWindow mUIStartmenuWindow;
        
        private UIItemWindow4 mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginSuccess'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class LoginSuccessParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'jleung{Tab}' in custom control
        /// </summary>
        public string UIItemCustomSendKeys = "jleung{Tab}";
        
        /// <summary>
        /// Type '1234{+}five' in custom control
        /// </summary>
        public string UIItemCustomSendKeys1 = "1234{+}five";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliWindow : WinWindow
    {
        
        public UIC4SerializationAppliWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "C4 Serialization Application - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            this.WindowTitles.Add("New Tab - Google Chrome");
            this.WindowTitles.Add("The resource cannot be found. - Google Chrome");
            this.WindowTitles.Add("ship-dev.control4.com/ship/Content/Login.aspx?ReturnUrl=%2fship%2fContent%2fScanS" +
                    "erialNumber.aspx - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIBookmarksToolBar UIBookmarksToolBar
        {
            get
            {
                if ((this.mUIBookmarksToolBar == null))
                {
                    this.mUIBookmarksToolBar = new UIBookmarksToolBar(this);
                }
                return this.mUIBookmarksToolBar;
            }
        }
        
        public UIAddressandsearchbarGroup UIAddressandsearchbarGroup
        {
            get
            {
                if ((this.mUIAddressandsearchbarGroup == null))
                {
                    this.mUIAddressandsearchbarGroup = new UIAddressandsearchbarGroup(this);
                }
                return this.mUIAddressandsearchbarGroup;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemTabList mUIItemTabList;
        
        private UIBookmarksToolBar mUIBookmarksToolBar;
        
        private UIAddressandsearchbarGroup mUIAddressandsearchbarGroup;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow3 mUIItemWindow3;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "134672896";
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinControl UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIItemDocument.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private WinControl mUIItemDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinButton UINewTabButton
        {
            get
            {
                if ((this.mUINewTabButton == null))
                {
                    this.mUINewTabButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINewTabButton.SearchProperties[WinButton.PropertyNames.Name] = "New Tab";
                    this.mUINewTabButton.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUINewTabButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINewTabButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIBookmarksToolBar : WinToolBar
    {
        
        public UIBookmarksToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Bookmarks";
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIControl4MenuButton
        {
            get
            {
                if ((this.mUIControl4MenuButton == null))
                {
                    this.mUIControl4MenuButton = new WinControl(this);
                    #region Search Criteria
                    this.mUIControl4MenuButton.SearchProperties[UITestControl.PropertyNames.Name] = "Control4";
                    this.mUIControl4MenuButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "MenuButton";
                    this.mUIControl4MenuButton.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIControl4MenuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIControl4MenuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIAddressandsearchbarGroup : WinGroup
    {
        
        public UIAddressandsearchbarGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address and search bar";
            this.WindowTitles.Add("The resource cannot be found. - Google Chrome");
            this.WindowTitles.Add("ship-dev.control4.com/ship/Content/Login.aspx?ReturnUrl=%2fship%2fContent%2fScanS" +
                    "erialNumber.aspx - Google Chrome");
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("The resource cannot be found. - Google Chrome");
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("ship-dev.control4.com/ship/Content/Login.aspx?ReturnUrl=%2fship%2fContent%2fScanS" +
                            "erialNumber.aspx - Google Chrome");
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "308775936";
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public WinControl UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIItemDocument.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        
        private WinControl mUIItemDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "308775936";
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "308775936";
            this.WindowTitles.Add("C4 Serialization Application - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIItemDocument.WindowTitles.Add("C4 Serialization Application - Google Chrome");
                    #endregion
                }
                return this.mUIItemDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIStartmenuWindow : WinWindow
    {
        
        public UIStartmenuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Start menu";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "ImmersiveLauncher";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public UIMailGroup UIMailGroup
        {
            get
            {
                if ((this.mUIMailGroup == null))
                {
                    this.mUIMailGroup = new UIMailGroup(this);
                }
                return this.mUIMailGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIMailGroup mUIMailGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIMailGroup : WinGroup
    {
        
        public UIMailGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Mail";
            this.WindowTitles.Add("Start menu");
            #endregion
        }
        
        #region Properties
        public WinListItem UIMailListItem
        {
            get
            {
                if ((this.mUIMailListItem == null))
                {
                    this.mUIMailListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIMailListItem.SearchProperties[WinListItem.PropertyNames.Name] = "Mail";
                    this.mUIMailListItem.WindowTitles.Add("Start menu");
                    #endregion
                }
                return this.mUIMailListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIMailListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_2";
            #endregion
        }
        
        #region Properties
        public UIShipToolMenuBar UIShipToolMenuBar
        {
            get
            {
                if ((this.mUIShipToolMenuBar == null))
                {
                    this.mUIShipToolMenuBar = new UIShipToolMenuBar(this);
                }
                return this.mUIShipToolMenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIShipToolMenuBar mUIShipToolMenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIShipToolMenuBar : WinMenuBar
    {
        
        public UIShipToolMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Ship Tool";
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinMenuItem UIWarehouseDevMenuItem
        {
            get
            {
                if ((this.mUIWarehouseDevMenuItem == null))
                {
                    this.mUIWarehouseDevMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIWarehouseDevMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Warehouse - Dev";
                    #endregion
                }
                return this.mUIWarehouseDevMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIWarehouseDevMenuItem;
        #endregion
    }
}
