// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ShipToolAutomatedU
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// SuccessfulLogin - Use 'SuccessfulLoginParams' to pass parameters into this method.
        /// </summary>
        public void SuccessfulLogin()
        {
            #region Variable Declarations
            BrowserWindow uIMSNWindowsInternetExWindow = this.UIMSNWindowsInternetExWindow;
            HtmlEdit uIUserNameEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIUserNameEdit1;
            HtmlEdit uIPasswordEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIPasswordEdit1;
            HtmlInputButton uILogInButton1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UILogInButton1;
            #endregion

            // Go to web page 'http://stage-c4sap01.control4.com/ship/Content/login.aspx'
            uIMSNWindowsInternetExWindow.NavigateToUrl(new System.Uri(this.SuccessfulLoginParams.UIMSNWindowsInternetExWindowUrl));

            // Type 'jleung' in 'UserName' text box
            uIUserNameEdit1.Text = this.SuccessfulLoginParams.UIUserNameEdit1Text;

            // Type '{Tab}' in 'UserName' text box
            Keyboard.SendKeys(uIUserNameEdit1, this.SuccessfulLoginParams.UIUserNameEdit1SendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit1.Password = this.SuccessfulLoginParams.UIPasswordEdit1Password;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit1, this.SuccessfulLoginParams.UIPasswordEdit1SendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Log In' button
            Keyboard.SendKeys(uILogInButton1, this.SuccessfulLoginParams.UILogInButton1SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Successful log in should redirect to the deliveries tab
        /// </summary>
        public void AssertSuccessfulLoginWithRedirect()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UIMSNWindowsInternetExWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            #endregion
            //TODO: Watch this item!!!
            // Verify that the 'ControlType' property of 'Address and search using Bing' text box matches 'http://stage-c4sap01.control4.com/ship/Content/ScanSerialNumber.aspx'
            StringAssert.Matches(uIAddressandsearchusinEdit.Text, new Regex(this.AssertSuccessfulLoginWithRedirectExpectedValues.UIAddressandsearchusinEditControlType), "Page did not redirect to Deliveries Tab");
        }
        
        /// <summary>
        /// SuccessfulLogOut
        /// </summary>
        public void SuccessfulLogOut()
        {
            #region Variable Declarations
            HtmlHyperlink uILogoutHyperlink = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument1.UIOb_em_mcTable.UILogoutHyperlink;
            #endregion

            // Click 'Logout' link
            Mouse.Click(uILogoutHyperlink, new Point(14, 8));
        }
        
        /// <summary>
        /// LoginFailure - Use 'LoginFailureParams' to pass parameters into this method.
        /// </summary>
        public void LoginFailure()
        {
            #region Variable Declarations
            HtmlHyperlink uILogbackinHyperlink = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument2.UILogbackinHyperlink;
            HtmlEdit uIUserNameEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIUserNameEdit1;
            HtmlEdit uIPasswordEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIPasswordEdit1;
            HtmlInputButton uILogInButton1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UILogInButton1;
            #endregion

            // Click 'Log back in.' link
            Mouse.Click(uILogbackinHyperlink, new Point(36, 7));

            // Type '1234abc' in 'UserName' text box
            uIUserNameEdit1.Text = this.LoginFailureParams.UIUserNameEdit1Text;

            // Type '{Tab}' in 'UserName' text box
            Keyboard.SendKeys(uIUserNameEdit1, this.LoginFailureParams.UIUserNameEdit1SendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit1.Password = this.LoginFailureParams.UIPasswordEdit1Password;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit1, this.LoginFailureParams.UIPasswordEdit1SendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Log In' button
            Keyboard.SendKeys(uILogInButton1, this.LoginFailureParams.UILogInButton1SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// AserrtErrorMessageDisplayedUponFailedLogIn - Use 'AserrtErrorMessageDisplayedUponFailedLogInExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AserrtErrorMessageDisplayedUponFailedLogIn()
        {
            #region Variable Declarations
            HtmlSpan uICtl00_MainContent_OuPane = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument3.UICtl00_MainContent_OuPane;
            #endregion

            // Verify that the 'Id' property of 'ctl00_MainContent_Output' pane contains 'Error authenticating. Error authenticating user. Logon failure: unknown user name or bad password. '
            StringAssert.Contains(uICtl00_MainContent_OuPane.Id, this.AserrtErrorMessageDisplayedUponFailedLogInExpectedValues.UICtl00_MainContent_OuPaneId);
        }
        
        /// <summary>
        /// LoadDeliveryMustBeANumber - Use 'LoadDeliveryMustBeANumberParams' to pass parameters into this method.
        /// </summary>
        public void LoadDeliveryMustBeANumber()
        {
            #region Variable Declarations
            HtmlEdit uIT1Edit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument1.UIT1Edit1;
            BrowserWindow uIMSNWindowsInternetExWindow = this.UIMSNWindowsInternetExWindow;
            #endregion

            // Type '123123x' in 't1' text box
            uIT1Edit1.Text = this.LoadDeliveryMustBeANumberParams.UIT1Edit1Text;

            // Type '{Tab}' in 't1' text box
            Keyboard.SendKeys(uIT1Edit1, this.LoadDeliveryMustBeANumberParams.UIT1Edit1SendKeys, ModifierKeys.None);

            // Click 'Ok' button in the browser dialog window
            uIMSNWindowsInternetExWindow.PerformDialogAction(BrowserDialogAction.Ok);
        }
        
        /// <summary>
        /// LoadDeliveryNotVerified - Use 'LoadDeliveryNotVerifiedParams' to pass parameters into this method.
        /// </summary>
        public void LoadDeliveryNotVerified()
        {
            #region Variable Declarations
            HtmlEdit uIT1Edit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument1.UIT1Edit1;
            #endregion

            // Type '123123' in 't1' text box
            uIT1Edit1.Text = this.LoadDeliveryNotVerifiedParams.UIT1Edit1Text;

            // Type '{Tab}' in 't1' text box
            Keyboard.SendKeys(uIT1Edit1, this.LoadDeliveryNotVerifiedParams.UIT1Edit1SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// AssertNonVerifiedDeliveryImageDisplayed - Use 'AssertNonVerifiedDeliveryImageDisplayedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertNonVerifiedDeliveryImageDisplayed()
        {
            #region Variable Declarations
            HtmlImage uIShipimagesNotVerifieImage = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument4.UIShipimagesNotVerifieImage;
            #endregion

            // Verify that the 'Id' property of '/ship/images/NotVerified_0.jpg' image equals 'NotVerified_0.jpg'
            Assert.AreEqual(this.AssertNonVerifiedDeliveryImageDisplayedExpectedValues.UIShipimagesNotVerifieImageId, uIShipimagesNotVerifieImage.Id, "Delivery was verified or was not found to be unverified. ");
        }
        
        /// <summary>
        /// PreliminaryLoginForTesting - Use 'PreliminaryLoginForTestingParams' to pass parameters into this method.
        /// </summary>
        public void PreliminaryLoginForTesting()
        {
            #region Variable Declarations
            BrowserWindow uIMSNWindowsInternetExWindow = this.UIMSNWindowsInternetExWindow;
            HtmlEdit uIUserNameEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIUserNameEdit1;
            HtmlEdit uIPasswordEdit1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UIPasswordEdit1;
            HtmlInputButton uILogInButton1 = this.UIMSNWindowsInternetExWindow.UIC4SerializationAppliDocument.UILogInButton1;
            #endregion

            // Go to web page 'http://stage-c4sap01.control4.com/ship/Content/login.aspx'
            uIMSNWindowsInternetExWindow.NavigateToUrl(new System.Uri(this.PreliminaryLoginForTestingParams.UIMSNWindowsInternetExWindowUrl));

            // Type 'jleung' in 'UserName' text box
            uIUserNameEdit1.Text = this.PreliminaryLoginForTestingParams.UIUserNameEdit1Text;

            // Type '{Tab}' in 'UserName' text box
            Keyboard.SendKeys(uIUserNameEdit1, this.PreliminaryLoginForTestingParams.UIUserNameEdit1SendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit1.Password = this.PreliminaryLoginForTestingParams.UIPasswordEdit1Password;

            // Type '{Tab}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit1, this.PreliminaryLoginForTestingParams.UIPasswordEdit1SendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Log In' button
            Keyboard.SendKeys(uILogInButton1, this.PreliminaryLoginForTestingParams.UILogInButton1SendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual SuccessfulLoginParams SuccessfulLoginParams
        {
            get
            {
                if ((this.mSuccessfulLoginParams == null))
                {
                    this.mSuccessfulLoginParams = new SuccessfulLoginParams();
                }
                return this.mSuccessfulLoginParams;
            }
        }
        
        public virtual AssertSuccessfulLoginWithRedirectExpectedValues AssertSuccessfulLoginWithRedirectExpectedValues
        {
            get
            {
                if ((this.mAssertSuccessfulLoginWithRedirectExpectedValues == null))
                {
                    this.mAssertSuccessfulLoginWithRedirectExpectedValues = new AssertSuccessfulLoginWithRedirectExpectedValues();
                }
                return this.mAssertSuccessfulLoginWithRedirectExpectedValues;
            }
        }
        
        public virtual LoginFailureParams LoginFailureParams
        {
            get
            {
                if ((this.mLoginFailureParams == null))
                {
                    this.mLoginFailureParams = new LoginFailureParams();
                }
                return this.mLoginFailureParams;
            }
        }
        
        public virtual AserrtErrorMessageDisplayedUponFailedLogInExpectedValues AserrtErrorMessageDisplayedUponFailedLogInExpectedValues
        {
            get
            {
                if ((this.mAserrtErrorMessageDisplayedUponFailedLogInExpectedValues == null))
                {
                    this.mAserrtErrorMessageDisplayedUponFailedLogInExpectedValues = new AserrtErrorMessageDisplayedUponFailedLogInExpectedValues();
                }
                return this.mAserrtErrorMessageDisplayedUponFailedLogInExpectedValues;
            }
        }
        
        public virtual LoadDeliveryMustBeANumberParams LoadDeliveryMustBeANumberParams
        {
            get
            {
                if ((this.mLoadDeliveryMustBeANumberParams == null))
                {
                    this.mLoadDeliveryMustBeANumberParams = new LoadDeliveryMustBeANumberParams();
                }
                return this.mLoadDeliveryMustBeANumberParams;
            }
        }
        
        public virtual LoadDeliveryNotVerifiedParams LoadDeliveryNotVerifiedParams
        {
            get
            {
                if ((this.mLoadDeliveryNotVerifiedParams == null))
                {
                    this.mLoadDeliveryNotVerifiedParams = new LoadDeliveryNotVerifiedParams();
                }
                return this.mLoadDeliveryNotVerifiedParams;
            }
        }
        
        public virtual AssertNonVerifiedDeliveryImageDisplayedExpectedValues AssertNonVerifiedDeliveryImageDisplayedExpectedValues
        {
            get
            {
                if ((this.mAssertNonVerifiedDeliveryImageDisplayedExpectedValues == null))
                {
                    this.mAssertNonVerifiedDeliveryImageDisplayedExpectedValues = new AssertNonVerifiedDeliveryImageDisplayedExpectedValues();
                }
                return this.mAssertNonVerifiedDeliveryImageDisplayedExpectedValues;
            }
        }
        
        public virtual PreliminaryLoginForTestingParams PreliminaryLoginForTestingParams
        {
            get
            {
                if ((this.mPreliminaryLoginForTestingParams == null))
                {
                    this.mPreliminaryLoginForTestingParams = new PreliminaryLoginForTestingParams();
                }
                return this.mPreliminaryLoginForTestingParams;
            }
        }
        
        public UIMSNWindowsInternetExWindow UIMSNWindowsInternetExWindow
        {
            get
            {
                if ((this.mUIMSNWindowsInternetExWindow == null))
                {
                    this.mUIMSNWindowsInternetExWindow = new UIMSNWindowsInternetExWindow();
                }
                return this.mUIMSNWindowsInternetExWindow;
            }
        }
        #endregion
        
        #region Fields
        private SuccessfulLoginParams mSuccessfulLoginParams;
        
        private AssertSuccessfulLoginWithRedirectExpectedValues mAssertSuccessfulLoginWithRedirectExpectedValues;
        
        private LoginFailureParams mLoginFailureParams;
        
        private AserrtErrorMessageDisplayedUponFailedLogInExpectedValues mAserrtErrorMessageDisplayedUponFailedLogInExpectedValues;
        
        private LoadDeliveryMustBeANumberParams mLoadDeliveryMustBeANumberParams;
        
        private LoadDeliveryNotVerifiedParams mLoadDeliveryNotVerifiedParams;
        
        private AssertNonVerifiedDeliveryImageDisplayedExpectedValues mAssertNonVerifiedDeliveryImageDisplayedExpectedValues;
        
        private PreliminaryLoginForTestingParams mPreliminaryLoginForTestingParams;
        
        private UIMSNWindowsInternetExWindow mUIMSNWindowsInternetExWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SuccessfulLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class SuccessfulLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://stage-c4sap01.control4.com/ship/Content/login.aspx'
        /// </summary>
        public string UIMSNWindowsInternetExWindowUrl = "http://stage-c4sap01.control4.com/ship/Content/login.aspx";
        
        /// <summary>
        /// Type 'jleung' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1Text = "jleung";
        
        /// <summary>
        /// Type '{Tab}' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1Password = "7Er0awXeZtxRYxNbIvOWA/XPmoTe+rDi";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Log In' button
        /// </summary>
        public string UILogInButton1SendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertSuccessfulLoginWithRedirect'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class AssertSuccessfulLoginWithRedirectExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Address and search using Bing' text box matches 'http://stage-c4sap01.control4.com/ship/Content/ScanSerialNumber.aspx'
        /// </summary>
        public string UIAddressandsearchusinEditControlType = "http://stage-c4sap01.control4.com/ship/Content/ScanSerialNumber.aspx";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginFailure'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class LoginFailureParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1234abc' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1Text = "1234abc";
        
        /// <summary>
        /// Type '{Tab}' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1Password = "m3S7XKTNpu+De6Z54Qz3MjVRG6U2y8rp";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Log In' button
        /// </summary>
        public string UILogInButton1SendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AserrtErrorMessageDisplayedUponFailedLogIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class AserrtErrorMessageDisplayedUponFailedLogInExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Id' property of 'ctl00_MainContent_Output' pane contains 'Error authenticating. Error authenticating user. Logon failure: unknown user name or bad password. '
        /// </summary>
        public string UICtl00_MainContent_OuPaneId = "Error authenticating. Error authenticating user. Logon failure: unknown user name" +
            " or bad password. ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoadDeliveryMustBeANumber'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class LoadDeliveryMustBeANumberParams
    {
        
        #region Fields
        /// <summary>
        /// Type '123123x' in 't1' text box
        /// </summary>
        public string UIT1Edit1Text = "123123x";
        
        /// <summary>
        /// Type '{Tab}' in 't1' text box
        /// </summary>
        public string UIT1Edit1SendKeys = "{Tab}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoadDeliveryNotVerified'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class LoadDeliveryNotVerifiedParams
    {
        
        #region Fields
        /// <summary>
        /// Type '123123' in 't1' text box
        /// </summary>
        public string UIT1Edit1Text = "123123";
        
        /// <summary>
        /// Type '{Tab}' in 't1' text box
        /// </summary>
        public string UIT1Edit1SendKeys = "{Tab}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertNonVerifiedDeliveryImageDisplayed'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class AssertNonVerifiedDeliveryImageDisplayedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Id' property of '/ship/images/NotVerified_0.jpg' image equals 'NotVerified_0.jpg'
        /// </summary>
        //TODO: Watch this item!!!
        public string UIShipimagesNotVerifieImageId = "ct100_MainContent_notverifiedimg";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PreliminaryLoginForTesting'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class PreliminaryLoginForTestingParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://stage-c4sap01.control4.com/ship/Content/login.aspx'
        /// </summary>
        public string UIMSNWindowsInternetExWindowUrl = "http://stage-c4sap01.control4.com/ship/Content/login.aspx";
        
        /// <summary>
        /// Type 'jleung' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1Text = "jleung";
        
        /// <summary>
        /// Type '{Tab}' in 'UserName' text box
        /// </summary>
        public string UIUserNameEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1Password = "7Er0awXeZtxRYxNbIvOWA/XPmoTe+rDi";
        
        /// <summary>
        /// Type '{Tab}' in 'Password' text box
        /// </summary>
        public string UIPasswordEdit1SendKeys = "{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Log In' button
        /// </summary>
        public string UILogInButton1SendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIMSNWindowsInternetExWindow : BrowserWindow
    {
        
        public UIMSNWindowsInternetExWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN");
            this.WindowTitles.Add("http://stage-c4sap01.control4.com/ship/Content/login.aspx");
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIC4SerializationAppliDocument UIC4SerializationAppliDocument
        {
            get
            {
                if ((this.mUIC4SerializationAppliDocument == null))
                {
                    this.mUIC4SerializationAppliDocument = new UIC4SerializationAppliDocument(this);
                }
                return this.mUIC4SerializationAppliDocument;
            }
        }
        
        public UIC4SerializationAppliDocument1 UIC4SerializationAppliDocument1
        {
            get
            {
                if ((this.mUIC4SerializationAppliDocument1 == null))
                {
                    this.mUIC4SerializationAppliDocument1 = new UIC4SerializationAppliDocument1(this);
                }
                return this.mUIC4SerializationAppliDocument1;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIAddressBarClient1 UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient1(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIC4SerializationAppliDocument2 UIC4SerializationAppliDocument2
        {
            get
            {
                if ((this.mUIC4SerializationAppliDocument2 == null))
                {
                    this.mUIC4SerializationAppliDocument2 = new UIC4SerializationAppliDocument2(this);
                }
                return this.mUIC4SerializationAppliDocument2;
            }
        }
        
        public UIC4SerializationAppliDocument3 UIC4SerializationAppliDocument3
        {
            get
            {
                if ((this.mUIC4SerializationAppliDocument3 == null))
                {
                    this.mUIC4SerializationAppliDocument3 = new UIC4SerializationAppliDocument3(this);
                }
                return this.mUIC4SerializationAppliDocument3;
            }
        }
        
        public UIC4SerializationAppliDocument4 UIC4SerializationAppliDocument4
        {
            get
            {
                if ((this.mUIC4SerializationAppliDocument4 == null))
                {
                    this.mUIC4SerializationAppliDocument4 = new UIC4SerializationAppliDocument4(this);
                }
                return this.mUIC4SerializationAppliDocument4;
            }
        }
        #endregion
        
        #region Fields
        private UIC4SerializationAppliDocument mUIC4SerializationAppliDocument;
        
        private UIC4SerializationAppliDocument1 mUIC4SerializationAppliDocument1;
        
        private UIItemWindow mUIItemWindow;
        
        private UIAddressBarClient1 mUIAddressBarClient;
        
        private UIC4SerializationAppliDocument2 mUIC4SerializationAppliDocument2;
        
        private UIC4SerializationAppliDocument3 mUIC4SerializationAppliDocument3;
        
        private UIC4SerializationAppliDocument4 mUIC4SerializationAppliDocument4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliDocument : HtmlDocument
    {
        
        public UIC4SerializationAppliDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "C4 Serialization Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ship/Content/login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stage-c4sap01.control4.com/ship/Content/login.aspx";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUserNameEdit
        {
            get
            {
                if ((this.mUIUserNameEdit == null))
                {
                    this.mUIUserNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_MainContent_UserName";
                    this.mUIUserNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$UserName";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_MainContent_UserName name=ctl00";
                    this.mUIUserNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIUserNameEdit.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIUserNameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_MainContent_Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "onkeypress=capLock(event) id=ctl00_MainC";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIPasswordEdit.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlInputButton UILogInButton
        {
            get
            {
                if ((this.mUILogInButton == null))
                {
                    this.mUILogInButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_MainContent_LoginBtn";
                    this.mUILogInButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$MainContent$LoginBtn";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Log In";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=ctl00_MainContent_LoginBtn type=submi";
                    this.mUILogInButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUILogInButton.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUILogInButton;
            }
        }
        
        public HtmlSpan UICtl00_MainContent_OuPane
        {
            get
            {
                if ((this.mUICtl00_MainContent_OuPane == null))
                {
                    this.mUICtl00_MainContent_OuPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICtl00_MainContent_OuPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_MainContent_Output";
                    this.mUICtl00_MainContent_OuPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Error authenticating. Error authenticati";
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=ctl00_MainContent_Output";
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
                    this.mUICtl00_MainContent_OuPane.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUICtl00_MainContent_OuPane;
            }
        }
        
        public HtmlEdit UIUserNameEdit1
        {
            get
            {
                if ((this.mUIUserNameEdit1 == null))
                {
                    this.mUIUserNameEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_MainContent_UserName";
                    this.mUIUserNameEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$UserName";
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$UserName\" id=\"ct";
                    this.mUIUserNameEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIUserNameEdit1.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIUserNameEdit1;
            }
        }
        
        public HtmlEdit UIPasswordEdit1
        {
            get
            {
                if ((this.mUIPasswordEdit1 == null))
                {
                    this.mUIPasswordEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_MainContent_Password";
                    this.mUIPasswordEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$MainContent$Password";
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$Password\" id=\"ct";
                    this.mUIPasswordEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIPasswordEdit1.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIPasswordEdit1;
            }
        }
        
        public HtmlInputButton UILogInButton1
        {
            get
            {
                if ((this.mUILogInButton1 == null))
                {
                    this.mUILogInButton1 = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILogInButton1.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_MainContent_LoginBtn";
                    this.mUILogInButton1.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$MainContent$LoginBtn";
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Log In";
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$MainContent$LoginBtn\" id=\"ct";
                    this.mUILogInButton1.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUILogInButton1.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUILogInButton1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUserNameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlInputButton mUILogInButton;
        
        private HtmlSpan mUICtl00_MainContent_OuPane;
        
        private HtmlEdit mUIUserNameEdit1;
        
        private HtmlEdit mUIPasswordEdit1;
        
        private HtmlInputButton mUILogInButton1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliDocument1 : HtmlDocument
    {
        
        public UIC4SerializationAppliDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "C4 Serialization Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ship/Content/ScanSerialNumber.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stage-c4sap01.control4.com/ship/Content/ScanSerialNumber.aspx";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIT1Edit
        {
            get
            {
                if ((this.mUIT1Edit == null))
                {
                    this.mUIT1Edit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIT1Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "deliverytext";
                    this.mUIT1Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "t1";
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "onchange=SubmitDelivery(this.form.t1.val";
                    this.mUIT1Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "9";
                    this.mUIT1Edit.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIT1Edit;
            }
        }
        
        public UIOb_em_mcTable UIOb_em_mcTable
        {
            get
            {
                if ((this.mUIOb_em_mcTable == null))
                {
                    this.mUIOb_em_mcTable = new UIOb_em_mcTable(this);
                }
                return this.mUIOb_em_mcTable;
            }
        }
        
        public HtmlEdit UIT1Edit1
        {
            get
            {
                if ((this.mUIT1Edit1 == null))
                {
                    this.mUIT1Edit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIT1Edit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "deliverytext";
                    this.mUIT1Edit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "t1";
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"t1\" id=\"deliverytext\" onchange=\"Su";
                    this.mUIT1Edit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIT1Edit1.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIT1Edit1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIT1Edit;
        
        private UIOb_em_mcTable mUIOb_em_mcTable;
        
        private HtmlEdit mUIT1Edit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIOb_em_mcTable : HtmlTable
    {
        
        public UIOb_em_mcTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "ob_em_mc";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Logout\r\n ";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "id=\"ob_em_mc\" style=\"width: 100%; height: 100%;\" cellspacing=\"0\" cellpadding=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "4";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "22";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILogoutHyperlink
        {
            get
            {
                if ((this.mUILogoutHyperlink == null))
                {
                    this.mUILogoutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogoutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Logout";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ship/Content/Logout.aspx";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://stage-c4sap01.control4.com/ship/Content/Logout.aspx";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/ship/Content/Logout.aspx\"";
                    this.mUILogoutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUILogoutHyperlink.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUILogoutHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILogoutHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "AddressDisplay Control";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressEdit
        {
            get
            {
                if ((this.mUIAddressEdit == null))
                {
                    this.mUIAddressEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address";
                    this.mUIAddressEdit.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIAddressEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIAddressBarClient1 : WinClient
    {
        
        public UIAddressBarClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliDocument2 : HtmlDocument
    {
        
        public UIC4SerializationAppliDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "C4 Serialization Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ship/Content/Logout.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stage-c4sap01.control4.com/ship/Content/Logout.aspx";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILogbackinHyperlink
        {
            get
            {
                if ((this.mUILogbackinHyperlink == null))
                {
                    this.mUILogbackinHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILogbackinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "ctl00_MainContent_hlLogin";
                    this.mUILogbackinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILogbackinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILogbackinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log back in.";
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ship/Content/login.aspx";
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://stage-c4sap01.control4.com/ship/Content/login.aspx";
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"ctl00_MainContent_hlLogin\" href=\"log";
                    this.mUILogbackinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "12";
                    this.mUILogbackinHyperlink.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUILogbackinHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILogbackinHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliDocument3 : HtmlDocument
    {
        
        public UIC4SerializationAppliDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "C4 Serialization Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ship/Content/Login.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stage-c4sap01.control4.com/ship/Content/Login.aspx?ReturnUrl=%2fship%2fCon" +
                "tent%2fLogout.aspx";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UICtl00_MainContent_OuPane
        {
            get
            {
                if ((this.mUICtl00_MainContent_OuPane == null))
                {
                    this.mUICtl00_MainContent_OuPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUICtl00_MainContent_OuPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_MainContent_Output";
                    this.mUICtl00_MainContent_OuPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Error authenticating. Error authenticati";
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"ctl00_MainContent_Output\"";
                    this.mUICtl00_MainContent_OuPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "3";
                    this.mUICtl00_MainContent_OuPane.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUICtl00_MainContent_OuPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUICtl00_MainContent_OuPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.51106.1")]
    public class UIC4SerializationAppliDocument4 : HtmlDocument
    {
        
        public UIC4SerializationAppliDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "C4 Serialization Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ship/Content/ScanSerialNumber.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://stage-c4sap01.control4.com/ship/Content/ScanSerialNumber.aspx?DeliveryNum=" +
                "123123";
            this.WindowTitles.Add("C4 Serialization Application");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIShipimagesNotVerifieImage
        {
            get
            {
                if ((this.mUIShipimagesNotVerifieImage == null))
                {
                    this.mUIShipimagesNotVerifieImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIShipimagesNotVerifieImage.SearchProperties[HtmlImage.PropertyNames.Id] = "ctl00_MainContent_notverifiedimg";
                    this.mUIShipimagesNotVerifieImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIShipimagesNotVerifieImage.SearchProperties[HtmlImage.PropertyNames.Alt] = null;
                    this.mUIShipimagesNotVerifieImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/ship/images/NotVerified_0.jpg";
                    this.mUIShipimagesNotVerifieImage.FilterProperties[HtmlImage.PropertyNames.Src] = "http://stage-c4sap01.control4.com/ship/images/NotVerified_0.jpg";
                    this.mUIShipimagesNotVerifieImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIShipimagesNotVerifieImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "id=\"ctl00_MainContent_notverifiedimg\" sr";
                    this.mUIShipimagesNotVerifieImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIShipimagesNotVerifieImage.WindowTitles.Add("C4 Serialization Application");
                    #endregion
                }
                return this.mUIShipimagesNotVerifieImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIShipimagesNotVerifieImage;
        #endregion
    }
}
